### ISSUE TITLE
unable to reproduce `PopSyCLE_example.ipynb`

### ISSUE THREAD

**Issue by rpoleski** [jluastro/PopSyCLE#59]
I'm trying to run `synthetic.perform_pop_syn()` as indicated in the manual. I don't know what should be the `iso_dir` value, so I've provided path to an empty folder. The output of the code:

```
/.../SPISEA/spisea/evolution.py:22: UserWarning: SPISEA_MODELS is undefined; functionality will be SEVERELY crippled.
  warnings.warn("SPISEA_MODELS is undefined; functionality "
******************** Starting popid 0
********** Starting log age bin 6.2
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 1 stars in bin
********** Starting log age bin 6.3
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 1 stars in bin
********** Starting log age bin 7.0
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 2 stars in bin
********** Starting log age bin 7.7
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 7 stars in bin
********** Starting log age bin 8.0
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
** Starting sub-bin  0 with 1 stars in bin
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 7 stars in bin
******************** Starting popid 1
********** Starting log age bin 8.2
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 41 stars in bin
********** Starting log age bin 8.4
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
** Starting sub-bin  0 with 1 stars in bin
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 79 stars in bin
********** Starting log age bin 8.6
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
** Starting sub-bin  0 with 2 stars in bin
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 218 stars in bin
********** Starting log age bin 8.8
***** Starting metallicity bin  -1.39
***** Starting metallicity bin  -0.89
***** Starting metallicity bin  -0.25
** Starting sub-bin  0 with 7 stars in bin
***** Starting metallicity bin  0.3
** Starting sub-bin  0 with 461 stars in bin
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.8/multiprocessing/pool.py", line 576, in _handle_results
    task = get()
  File "/usr/lib64/python3.8/multiprocessing/connection.py", line 255, in recv
    return _ForkingPickler.loads(buf.getbuffer())
TypeError: __init__() missing 2 required positional arguments: 'grid_num' and 'model_type'
```
At that point, the code efficiently stopped. Can someone help with that?

**Comment by nsabrams** [comment]
As part of the SPISEA installation (which is a requirement for PopSyCLE), you need to download the stellar evolution and atmosphere models and then point to them in your .zshenv or .bash_profile. You can see instructions here https://spisea.readthedocs.io/en/latest/getting_started.html in sections "Stellar Evolution and Atmosphere Models" and "Set Paths to Models". 

With regard to the iso_dir, you can put the path as any folder you'd like. It's helpful to have a designated location that you consistently use between PopSyCLE runs. This will be the directory where isochrones will be generated and stored and reused in future runs. The first time you run perform_pop_syn on a patch with new ages or metallicities, it will generate new isochrones and take a bit longer.

**Comment by rpoleski** [comment]
Thanks - the warning is gone after I provided the paths (previously I've stopped reading installation instructions too soon).
Yet, I'm still getting the same error at the end. Any idea what's the cause of that?

**Comment by nsabrams** [comment]
Hmm, in the past when we've run into this error, SPISEA was unsuccessfully trying to raise this ModelMismatch exception https://github.com/astropy/SPISEA/blob/main/spisea/exceptions.py and downloading the newest models fixed it. Are you using the files from the SPISEA install or some other download from STScI CDBS? Also, what are your paths for PYSYN_CDBS and SPISEA_MODELS?

**Comment by rpoleski** [comment]
Ok, calculations are runnng now. I've corrected `SPISEA_MODELS` to point one level higher than the `evolution/` dir. Thanks.

**Comment by nsabrams** [comment]
Awesome, I'll close the issue then
